[project]
name = "weather-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.57.1",
    "mcp>=1.10.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
